version: '3'
services:
  payara:
    build: ./payara/
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ../../target/:/opt/payara/deployments/
  mysql:
    build: ./mysql/
    restart: always
    ports:
      - "3306:3306"
